# Generated by Django 4.2.16 on 2024-10-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
