# Generated by Django 4.2.16 on 2024-10-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_complaint_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='helprequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('reply', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
