# Generated by Django 4.2.16 on 2024-10-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_supplycosubmit_alter_complaint_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplyconotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=20, null=True)),
                ('notification', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
