# Generated by Django 4.2.16 on 2024-11-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_supplycostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopstockbooking',
            name='bookingstatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
