# Generated by Django 4.2.16 on 2024-11-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_shopstockbooking_bookingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyconotification',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
