# Generated by Django 4.2.16 on 2024-11-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_supplyconotification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyconotification',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplyconotification',
            name='notification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplyconotification',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplyconotification',
            name='userid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
