# Generated by Django 4.2.16 on 2024-11-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_supplyconotification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='status',
            field=models.CharField(blank=True, default='REJECT', max_length=20, null=True),
        ),
    ]
