# Generated by Django 4.2.16 on 2024-10-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_userprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('loginid', models.CharField(blank=True, max_length=20, null=True)),
                ('bookingdate', models.CharField(blank=True, max_length=20, null=True)),
                ('bookingtime', models.CharField(blank=True, max_length=20, null=True)),
                ('products', models.CharField(blank=True, max_length=20, null=True)),
                ('deliverystatus', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('DEACTIVE', 'Deactive'), ('ACTIVE', 'Active')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('ADMIN', 'Admin'), ('INSTITUTE', 'Institute')], max_length=20),
        ),
    ]
